# Site settings
title: main = putStrLn . blog me
email: jim.holmstroem@gmail.com
description: >
  A blog about data analysis, Python, functional programming and programming in general.
baseurl: ""
url: "http://jim-holmstroem.github.io"
twitter_username: JimHolmstroem
github_username:  jim-holmstroem

# Build settings
markdown: kramdown
